# Generated by Django 5.2.5 on 2025-08-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("PAYMENT", "Payment"), ("FINE", "Fine")],
                default="PAYMENT",
                max_length=10,
            ),
        ),
    ]
