# Generated by Django 5.2.5 on 2025-08-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0002_payment_status_payment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="session_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
