# Generated by Django 5.2.5 on 2025-08-16 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Book name", max_length=255)),
                ("pub_date", models.DateTimeField(help_text="Publication date")),
                (
                    "author",
                    models.CharField(help_text="Author full name", max_length=255),
                ),
                (
                    "cover",
                    models.CharField(
                        choices=[("HARD", "Hardcover"), ("SOFT", "Softcover")],
                        default="HARD",
                        help_text="Cover type",
                        max_length=4,
                    ),
                ),
                (
                    "inventory",
                    models.PositiveIntegerField(default=1, help_text="Inventory"),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=2, help_text="Daily fee in usd $", max_digits=5
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ("-pub_date",),
            },
        ),
    ]
