name: Django Docker CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Create .env file
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "STRIPE_API_KEY=${{ secrets.STRIPE_API_KEY }}" >> .env
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env
        echo "CELERY_BROKER_URL=${{ secrets.CELERY_BROKER_URL }}" >> .env
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version
    
    - name: Build and start containers
      run: |
        docker-compose up -d --build

    - name: Run Django tests
      run: |
        docker-compose exec -T web python manage.py test tests

    - name: Stop and remove containers
      if: always()
      run: |
        docker-compose down -v
